name: Publish to GitHub Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        # runs-on: self-hosted
        runs-on: macos-11
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v2
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: "^13.2.1"
            - uses: ruby/setup-ruby@v1
              env:
                ImageOS: macos11
              with:
                ruby-version: 3.1
                bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Generate docs
              run: bundle exec jazzy --module SwifterSwiftSSH --copyright "This project is licensed under the [MIT License](https://github.com/ridenui/swifter-swift-ssh/blob/main/LICENSE)."
            - name: Upload Artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: docs
                  path: docs
    deploy:
        concurrency: ci-${{ github.ref }}
        needs: [build]
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, 'chore(release): ')"
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
            - name: Download Artifacts
              uses: actions/download-artifact@v1
              with:
                  name: docs
            - name: Publish generated content to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  folder: docs
                  branch: gh-pages
                  token: ${{ secrets.ACCESS_TOKEN }}
