# This is a basic workflow to help you get started with Actions

name: publish-to-cocoapods

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    publish:
        # The type of runner that the job will run on
        runs-on: macOS-latest

        if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: "^13.2.1"

            - uses: fwal/setup-swift@v1
              with:
                  swift-version: "5.5.2"

            - name: Get swift version
              run: swift --version

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              with:
                  extra_plugins: |
                      semantic-release-cocoapods
                      @semantic-release/release-notes-generator
                      @semantic-release/github
              env:
                  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.HIGH5_BOT_TOKEN }}
                  GIT_AUTHOR_NAME: "high5-bot"
                  GIT_AUTHOR_EMAIL: "me+high5@dunklestoast.de"
                  GIT_COMMITTER_NAME: "high5-bot"
                  GIT_COMMITTER_EMAIL: "me+high5@dunklestoast.de"
