name: basic-testing

on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches:
            - "*" # matches every branch that doesn't contain a '/'
            - "*/*" # matches every branch containing a single '/'
            - "**" # matches every branch
            - "!main"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    # This workflow contains a single job called "build"
    test:
        # The type of runner that the job will run on
        runs-on: self-hosted

        if: "!startsWith(github.event.head_commit.message, 'chore(release): ')"

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.HIGH5_BOT_TOKEN }}

            - name: Configuring Git and NPM
              run: |
                  git config --global user.name "high5-bot"
                  git config --global user.email "me+high5@dunklestoast.de"

            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: "^13.2.1"

            - uses: fwal/setup-swift@v1
              with:
                  swift-version: "5.5.2"

            - name: Get swift version
              run: swift --version

            - name: Install Cocoapods
              run: gem install cocoapods

            - name: Build lib
              run: pod lib lint --allow-warnings --use-libraries --verbose
